__title__ = "dinterpol"
__version__ = "0.3.1"
__summary__ = "data interpolation templating engine"
__uri__ = "https://github.com/Openpipe/dinterpol"
__author__ = "João Pinto"
__email__ = "lamego.pinto@gmail.com"
__license__ = "Apache-2"
